apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  username: Z2F1cmF2
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  db_server: 10.10.10.10
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: secret-demo-pod-container
      image: nginx
      envFrom:
        - secretRef:
            name: secret-demo
        - configMapRef:
            name: configmap-demo
