apiVersion: v1
kind: Service
metadata:
  name: basic-pod-service
  labels:
    app: nginx
    tier: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 80
      protocol: TCP
