apiVersion: v1
kind: Pod
metadata:
  name: basic-pod-apache
  labels:
    app: apache
    tier: frontend
spec:
  containers:
    - name: basic-pod-apache-container
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP
