apiVersion: v1
kind: Pod
metadata:
  name: basic-pod-nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: basic-pod-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
