apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-subpath #this name and configmap in volumes must be same
data:
  sample.html: |
    <h1>This</h1>
    <h2>is</h2>
    <h3>sample</h3>
    <h4>file</h4>
---
apiVersion: v1
kind: Service
metadata:
  name: configmap-subpath-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-subpath-pod
  labels:
    app: nginx
spec:
  containers:
    - name: configmap-subpath-pod-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: configmap-subpath-volume #volumes and volumeMounts name must be same
          mountPath: /usr/share/nginx/html/sample.html
          subPath: sample.html
  volumes:
    - name: configmap-subpath-volume #volumes and volumeMounts name must be same
      configMap:
        name: configmap-subpath #this name and configmap must be same
        items:
          - key: "sample.html"
            path: "sample.html"
