apiVersion: v1
kind: Service
metadata:
  name: configmap-nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
data:
  index.html: |
    Hello world.
    This is test line.
    EOL
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-nginx-demo
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: nginx-volume
          readOnly: true
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-volume
      configMap:
        name: configmap-nginx
        items:
          - key: "index.html"
            path: "index.html"
