apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  username: gaurav
  password: ubuntu
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: configmap-demo-container
      image: ubuntu:22.04
      args:
        - sleep
        - 360s
      envFrom:
        - configMapRef:
            name: configmap-demo
