apiVersion: apps/v1
metadata:
  name: {{ .Values.labels.app }}-deployment
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
kind: Deployment
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      {{- include "myapp.matchlabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}-container
          image: {{ .Values.containers.image }}
          env:
            - name: key1
              valueFrom:
                configMapKeyRef:
                  name: myapp-configmap
                  key: key1
            - name: key2
              valueFrom:
                configMapKeyRef:
                  name: myapp-configmap
                  key: key2
          ports:
            - containerPort: 80
              protocol: TCP
