apiVersion: v1
kind: Pod
metadata:
  name: liveness-prob-demo
  labels:
    app: liveness-test
spec:
  containers:
    - name: liveness-prob-demo-contaier
      image: registry.k8s.io/busybox:1.27.2
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
