apiVersion: v1
kind: Pod
metadata:
  name: readiness-exec-pod-demo
  labels:
    app: readiness-exec-pod-demo-app
spec:
  containers:
    - name: readiness-exec-pod-demo-container
      image: nginx
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/health
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 5
      ports:
        - containerPort: 80
          protocol: TCP
