apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  labels:
    app: nginx
    tier: frontend
data:
  index.html: |
    Ok!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap-2
  labels:
    app: nginx
    tier: frontend
data:
  config: |
    [default]
    region = ap-south-1
  credentials: |
    [default]
    aws_access_key_id = 
    aws_secret_access_key =
  sync.sh: |
    aws s3 sync /var/log/nginx s3://catalog-03082025
