apiVersion: v1
kind: Service
metadata:
  name: multi-init-container-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-init-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: multi-init-container-pod
      labels:
        app: nginx
    spec:
      initContainers:
        - name: dbconnection-container
          image: maxpain62/alpine:netcat
          command:
            - /bin/sh
          args:
            - -c
            - |
            - until nc -z <db-server-ip> <db-server-port>;
              do echo 'checking db connection'; sleep 5s;
              done
        - name: service-connection-container
          image: curlimages/curl:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
            - until curl multi-init-container-service.default.svc.cluster.local:80;
              do echo 'checking service connection'; sleep 5s;
              done
      containers:
        - name: main-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
