apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-demo
spec:
  minAvailable: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
          - backend
          - detabase
