apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod-affinity-antiaffinity-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      name: node-pod-affinity-antiaffinity-pod
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: node-pod-affinity-antiaffinity-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: instancetype
                    operator: In
                    values:
                      - mseries
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchExpressions:
                    - key: tier
                      operator: In
                      values:
                        - backend
                        - database
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - frontend
                  - key: app
                    operator: In
                    values:
                      - nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod-affinity-antiaffinity-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      name: node-pod-affinity-antiaffinity-pod-2
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: node-pod-affinity-antiaffinity-container-2
          image: busybox
          command: ["sleep", "3600s"]
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: instancetype
                    operator: In
                    values:
                      - rseries
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mysql
                  tier: database
              topologyKey: kubernetes.io/hostname
