apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-hard-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      name: pod-affinity-hard-deployment-2-pod
      labels:
        app: mysql
        tier: database
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    tier: frontend
                topologyKey: kubernetes.io/hostname
      containers:
        - name: pod-affinity-hard-container-2
          image: busybox
          command: ["sleep", "3600s"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-hard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      name: pod-affinity-hard-pdo
      labels:
        app: nginx
        tier: frontend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tier: database
              topologyKey: kubernetes.io/hostname
      containers:
        - name: pod-affinity-hard-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
