apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-demo-configmap
data:
  config: |
    [default]
    region = ap-south-1
  credentials: |
    [default]
<<<<<<< HEAD
    enter access key id here
    enter secret access key here
=======
    <add access key id>
    <add secret access key>
>>>>>>> 131aa71 (first commit)
  sync.sh: |
    aws s3 sync /var/log/nginx s3://catalog-03082025
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-demo-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo-pod
  labels:
    app: nginx
spec:
  containers:
    - name: sidecar-demo-container-log-shipper
      image: maxpain62/ubuntu-24.04:awscli-1.42.37
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "cp /tmp/sync.sh /root/sync.sh; chmod 777 /root/sync.sh; while true; do bash /root/sync.sh; sleep 10s; done",
        ]
      volumeMounts:
        - name: sidecar-demo-volume
          mountPath: /root/.aws/config
          subPath: config
        - name: sidecar-demo-volume
          mountPath: /root/.aws/credentials
          subPath: credentials
        - name: sidecar-demo-volume
          mountPath: /tmp/sync.sh
          subPath: sync.sh
        - name: sidecar-demo-logs
          mountPath: /var/log/nginx
    - name: sidecar-demo-container-nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: sidecar-demo-logs
          mountPath: /var/log/nginx
  volumes:
    - name: sidecar-demo-logs
      emptyDir: {}
    - name: sidecar-demo-volume
      configMap:
        name: sidecar-demo-configmap
