apiVersion: v1
kind: ServiceAccount
metadata:
  name: revision-sa-with-iam-role
  namespace: revision-namespace
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::134448505602:role/service-account-role"
