apiVersion: v1
kind: Service
metadata:
  name: revision-service
  namespace: revision-namespace
  labels: 
    app: web
    tier: frontend
spec:
  type: NodePort
  selector:
    app: web
    tier: frontend
  ports:
    - port: 80
      protocol: TCP
