apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: revision-hpa
  namespace: revision-namespace
  labels:
    app: web
    tier: frontend
spec:
  minReplicas: 3
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - periodSeconds: 30
          type: Pods
          value: 2
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - periodSeconds: 30
          type: Pods
          value: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: revision-deployment
