apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: revision-pdb
  namespace: revision-namespace
  labels:
    app: web
    tier: frontend
spec:
  minAvailable: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - web
