apiVersion: v1
kind: ConfigMap
metadata:
  name: hpa-demo-config-map
data:
  index.html: |
    OK!
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo-deployment
spec:
  #replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: hpa-demo-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: hpa-demo-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: hpa-demo-volume
              mountPath: /usr/share/nginx/html/
          resources:
            requests:
              cpu: "10m"
              memory: 10Mi
            limits:
              cpu: "20m"
              memory: 20Mi
      volumes:
        - name: hpa-demo-volume
          configMap:
            name: hpa-demo-config-map
