apiVersion: v1
kind: ConfigMap
metadata:
  name: init-container-demo-configmap
data:
  dbservername: "15.206.79.206"
  dbport: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: init-container-demo-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: init-container-demo-pod
      labels:
        app: webapp
    spec:
      initContainers:
        - name: init-container
          image: maxpain62/alpine:netcat
          envFrom:
            - configMapRef:
                name: init-container-demo-configmap
          command:
            [
              "sh",
              "-c",
              "until nc -z $(dbservername) $(dbport); do echo 'db is up'; done",
            ]
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
