apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-storage-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: statefulset-storage-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: statefulset-storage-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: statefulset-storage-class
        resources:
          requests:
            storage: 1Gi
