apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rolling-update-config-map
data:
  index.html: |
    1.27.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rolling-update-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rolling-update-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-deployment
  labels:
    app: web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  replicas: 8
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: rolling-update-pod
      labels:
        app: web
    spec:
      volumes:
        - name: rolling-update-volume
          configMap:
            name: rolling-update-config-map
      containers:
        - name: rolling-update-container
          image: nginx:1.27.0-alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rolling-update-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
