apiVersion: v1
kind: ServiceAccount
metadata:
  name: alpine-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alpine-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/exec"
      - "pods/log"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alpine-role-binding
subjects:
  - kind: ServiceAccount
    name: alpine-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alpine-role
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  serviceAccountName: alpine-service-account
  containers:
    - name: alpine-container
      image: tomcat:9-jdk11
