apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test-container-1
      image: ubuntu
      command: ["sleep", "3600s"]
    - name: test-container-2
      image: ubuntu
      command: ["sleep", "3600s"]
