apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configmap
data:
  index.php: |
    <?php
    phpinfo();
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: php-pod
  labels:
    app: php-app
spec:
  containers:
    - name: php-pod-container
      image: php:8.1.33-apache
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: php-index
          mountPath: /var/www/html
  volumes:
    - name: php-index
      configMap:
        name: php-configmap
