apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat-container
      image: tomcat:9-jdk11
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
    - port: 8080
