apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-demo
  namespace: namespace-demo
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
